version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 2
    directories: 
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    reviewers:
      - "@Aprende-com/moodle-dev"

  - package-ecosystem: "composer"
    open-pull-requests-limit: 2
    directories: 
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    reviewers:
      - "@Aprende-com/moodle-dev"