--- # 2024 08 13

name: "Plugin Dependency Version Validator"
on:
  pull_request:
    paths-ignore:
      - '.github/**'
    branches:
      - master

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MOODLE_LOCAL: moodle-dev
  

jobs:
  config_version_validation:
    runs-on: ubuntu-latest
    outputs:
      plugin_repo: ${{ steps.config.outputs.PLUGIN_REPO }}
      plugin_ref: ${{ steps.config.outputs.PLUGIN_REF }}
      plugin_path: ${{ steps.config.outputs.PLUGIN_PATH }}

    steps:

      - run: |
          echo "PLUGIN_REPO=$GITHUB_REPOSITORY" | tee -a "${GITHUB_ENV}"
          echo "PLUGIN_REF=$GITHUB_HEAD_REF" | tee -a "${GITHUB_ENV}"

      - name: "Generate Github App Token"
        uses: Aprende-com/devops-workflows/actions/generate-github-token@main
        id: app-token
        with:
          secret_key: ${{ secrets.DEVOPS_APP_SECRET_KEY }}
          app_id: ${{ secrets.DEVOPS_APP_ID }}

      - uses: Aprende-com/devops-workflows/actions/lms/plugin/getpath@main
        with:
          token: ${{ steps.app-token.outputs.token }}

      - id: config
        run: |
          echo "PLUGIN_REPO=${{ env.PLUGIN_REPO }}" >> $GITHUB_OUTPUT
          echo "PLUGIN_REF=${{ env.PLUGIN_REF }}" >> $GITHUB_OUTPUT
          echo "PLUGIN_PATH=${{ env.PLUGIN_PATH }}" >> $GITHUB_OUTPUT

  dependency_test:
    runs-on: ubuntu-latest
    needs: [config_version_validation]

    env:
      PLUGIN_REPO: ${{ needs.config_version_validation.outputs.plugin_repo }}
      PLUGIN_REF: ${{ needs.config_version_validation.outputs.plugin_ref }}
      PLUGIN_PATH: ${{ needs.config_version_validation.outputs.plugin_path }}

    steps:

      - name: "set config"
        run: |
          echo "PLUGIN_REPO=$GITHUB_REPOSITORY" | tee -a "${GITHUB_ENV}"
          echo "PLUGIN_REF=$GITHUB_HEAD_REF" | tee -a "${GITHUB_ENV}"

      - name: "Generate Github App Token"
        uses: Aprende-com/devops-workflows/actions/generate-github-token@main
        id: app-token
        with:
          secret_key: ${{ secrets.DEVOPS_APP_SECRET_KEY }}
          app_id: ${{ secrets.DEVOPS_APP_ID }}
          #repositories: "moodle-dev,${{ env.PLUGIN_REPO }}"

      - name: "moodle-dev: clone"
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: Aprende-com/moodle-dev
          path: "moodle-dev"
          
      - name: "plugin: clone"
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ env.PLUGIN_REPO }}
          path: moodle-dev/${{ env.PLUGIN_PATH }}
          ref: ${{ env.PLUGIN_REF }}

      - name: "devops/plugins: get submodule URLs"
        run: |
          cd moodle-dev
          PLUGIN_URLS=$(grep "aprende = true" .gitmodules -B1 | grep -v "aprende = true\|\-\-"   | awk '{FS="="} {print $2}' |sed 's/\.git/\/master\/version.php/g' |sed 's/git\@github.com\:/https\:\/\/raw\.githubusercontent\.com\//g'|awk '{FS=" "} {print $1}'|sed 's/\=//g' )
          PLUGIN_URLS=$(echo ${PLUGIN_URLS})  # Remove newlines
          echo "PLUGIN_URLS=${PLUGIN_URLS}" | tee -a "${GITHUB_ENV}"
          
      - name: "compare plugin versions"
        uses: Aprende-com/devops-workflows/actions/lms/version-validator@main
        with:
          path: "moodle-dev/${{ env.PLUGIN_PATH }}"
          urls: ${{ env.PLUGIN_URLS }}
          token: "token ${{ steps.app-token.outputs.token }}"
          
