--- # 2024 08 13

name: "PHPUnit"
on:
  pull_request:
    paths-ignore:
      - '.github/**'
    branches:
      - master
      - main

env:
  MOODLE_LOCAL: moodle-dev

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      plugin_repo: ${{ steps.config.outputs.PLUGIN_REPO }}
      plugin_ref: ${{ steps.config.outputs.PLUGIN_REF }}
      plugin_path: ${{ steps.config.outputs.PLUGIN_PATH }}

    steps:

      - run: |
          echo "PLUGIN_REPO=$GITHUB_REPOSITORY" | tee -a "${GITHUB_ENV}"
          echo "PLUGIN_REF=$GITHUB_HEAD_REF" | tee -a "${GITHUB_ENV}"

      - name: "Generate Github App Token"
        uses: Aprende-com/devops-workflows/actions/generate-github-token@main
        id: app-token
        with:
          secret_key: ${{ secrets.DEVOPS_APP_SECRET_KEY }}
          app_id: ${{ secrets.DEVOPS_APP_ID }}
          #repositories: "moodle-dev"

      - uses: Aprende-com/devops-workflows/actions/lms/plugin/getpath@main
        with:
          token: ${{ steps.app-token.outputs.token }}

      - id: config
        run: |
          echo "PLUGIN_REPO=${{ env.PLUGIN_REPO }}" >> $GITHUB_OUTPUT
          echo "PLUGIN_REF=${{ env.PLUGIN_REF }}" >> $GITHUB_OUTPUT
          echo "PLUGIN_PATH=${{ env.PLUGIN_PATH }}" >> $GITHUB_OUTPUT

  phpunit:
    runs-on: ubuntu-latest
    needs: [config]

    env:
      PLUGIN_REPO: ${{ needs.config.outputs.plugin_repo }}
      PLUGIN_REF: ${{ needs.config.outputs.plugin_ref }}
      PLUGIN_PATH: ${{ needs.config.outputs.plugin_path }}

    steps:

      - name: "setting up runner"
        uses: Aprende-com/devops-workflows/actions/lms/runner-config@main

      - name: "Generate Github App Token"
        uses: Aprende-com/devops-workflows/actions/generate-github-token@main
        id: app-token
        with:
          secret_key: ${{ secrets.DEVOPS_APP_SECRET_KEY }}
          app_id: ${{ secrets.DEVOPS_APP_ID }}
          #repositories: "moodle-dev,devops-workflows,${{ env.PLUGIN_REPO }}"

      - name: "cloning moodle-dev"
        uses: Aprende-com/devops-workflows/actions/lms/core-clone@main
        with:
          submodules: true
          token: ${{ steps.app-token.outputs.token }}

      - name: "plugin: clone"
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ env.PLUGIN_REPO }}
          path: moodle-dev/${{ env.PLUGIN_PATH }}
          ref: ${{ env.PLUGIN_REF }}

      - name: "plugin: run composer"
        uses: Aprende-com/devops-workflows/actions/lms/plugin/composer@main

      - name: "Run PHPUnit"
        uses: Aprende-com/devops-workflows/actions/lms/plugin/phpunit@main
        with:
          token: ${{ steps.app-token.outputs.token }}
