--- # 2023 03 02

name: "PHPUnit"
on:
  pull_request:
    paths-ignore:
      - '.github/**'
    branches:
      - master
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  # Comment to use 
  # AWS_REGION: us-east-1
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MOODLE_LOCAL: moodle-dev

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      plugin_repo: ${{ steps.config.outputs.PLUGIN_REPO }}
      plugin_ref: ${{ steps.config.outputs.PLUGIN_REF }}
      plugin_path: ${{ steps.config.outputs.PLUGIN_PATH }}

    steps:

      - name: "devops: checkout"
        uses: actions/checkout@v4
        with:
          repository: Aprende-com/devops-actions
          path: devops-actions
          token: ${{ env.GITHUB_TOKEN }}

      - run: |
          echo "PLUGIN_REPO=$GITHUB_REPOSITORY" | tee -a "${GITHUB_ENV}"
          echo "PLUGIN_REF=$GITHUB_HEAD_REF" | tee -a "${GITHUB_ENV}"

      - uses: ./devops-actions/lms/plugin-getpath

      - id: config
        run: |
          echo "PLUGIN_REPO=${{ env.PLUGIN_REPO }}" >> $GITHUB_OUTPUT
          echo "PLUGIN_REF=${{ env.PLUGIN_REF }}" >> $GITHUB_OUTPUT
          echo "PLUGIN_PATH=${{ env.PLUGIN_PATH }}" >> $GITHUB_OUTPUT

  phpunit:
    runs-on: ubuntu-latest
    needs: [config]

    env:
      PLUGIN_REPO: ${{ needs.config.outputs.plugin_repo }}
      PLUGIN_REF: ${{ needs.config.outputs.plugin_ref }}
      PLUGIN_PATH: ${{ needs.config.outputs.plugin_path }}

    steps:
      - name: "devops: checkout"
        uses: actions/checkout@v4
        with:
          repository: Aprende-com/devops-actions
          path: devops-actions
          token: ${{ env.GITHUB_TOKEN }}

      - name: "setting up runner"
        uses: ./devops-actions/lms/runner-config
        
      - name: "cloning moodle-dev"
        uses: ./devops-actions/lms/core-clone
        with:
          submodules: true  

      - name: "plugin: clone"
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          repository: ${{ env.PLUGIN_REPO }}
          path: moodle-dev/${{ env.PLUGIN_PATH }}
          ref: ${{ env.PLUGIN_REF }}

      - name: "plugin: run composer"
        uses: ./devops-actions/lms/plugin/composer

      - name: "Run PHPUnit"
        uses: ./devops-actions/lms/plugin-phpunit
