--- # 2022 05 26

name: "PHPUnit"
on:
  pull_request:
    branches:
      - master
      - main

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  MOODLE_LOCAL: moodle-dev

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      plugin_repo: ${{ steps.config.outputs.PLUGIN_REPO }}
      plugin_ref: ${{ steps.config.outputs.PLUGIN_REF }}
      plugin_path: ${{ steps.config.outputs.PLUGIN_PATH }}

    steps:

      - name: "devops: checkout"
        uses: actions/checkout@v3
        with:
          repository: Aprende-com/devops-actions
          path: devops-actions
          token: ${{ env.GITHUB_TOKEN }}

      - run: |
          echo "PLUGIN_REPO=$GITHUB_REPOSITORY" | tee -a "${GITHUB_ENV}"
          echo "PLUGIN_REF=$GITHUB_HEAD_REF" | tee -a "${GITHUB_ENV}"

      - uses: ./devops-actions/lms/plugin-getpath

      - id: config
        run: |
          echo "::set-output name=PLUGIN_REPO::${PLUGIN_REPO}"
          echo "::set-output name=PLUGIN_REF::${PLUGIN_REF}"
          echo "::set-output name=PLUGIN_PATH::${PLUGIN_PATH}"

  phpunit:
    runs-on: ubuntu-latest
    needs: [config]

    env:
      PLUGIN_REPO: ${{ needs.config.outputs.plugin_repo }}
      PLUGIN_REF: ${{ needs.config.outputs.plugin_ref }}
      PLUGIN_PATH: ${{ needs.config.outputs.plugin_path }}

    steps:
      - name: "devops: checkout"
        uses: actions/checkout@v3
        with:
          repository: Aprende-com/devops-actions
          path: devops-actions
          token: ${{ env.GITHUB_TOKEN }}

      - name: "setting up runner"
        uses: ./devops-actions/lms/runner-config
        
      - name: "cloning moodle-dev"
        uses: ./devops-actions/lms/core-clone
        with:
          submodules: true  

      - name: "get submodule paths"
        shell: bash
        run: |
          cd "${MOODLE_LOCAL}"       
          SUBMODULES_PATH=$(git submodule foreach pwd | grep -oP "(?<=')[^']+(?=')")
          SUBMODULES_PATH=$(echo ${SUBMODULES_PATH})  # Remove newlines
          echo "SUBMODULES_PATH=${SUBMODULES_PATH}" | tee -a "${GITHUB_ENV}"
      
      - name: Checkout submodules
        shell: bash
        run: |
          cd moodle-dev
          for SUBMODULES_PATH in ${SUBMODULES_PATH}; do
            cd "${SUBMODULES_PATH}"
            pwd
            git status
            git checkout ${{ env.PLUGIN_REF }} || true
            cd - > /dev/null
          done

      - name: "plugin: run composer"
        uses: ./devops-actions/lms/plugin/composer

      - name: "Run PHPUnit"
        uses: ./devops-actions/lms/plugin-phpunit

