---  # 2024 09 17

name: "Single Plugin Pipeline Dispatch"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # required

jobs:
  single_plugin_pipeline_dispatch:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    outputs:
      ISSUE_ID: ${{ steps.prepare_environment.outputs.ISSUE_ID }}
      HEAD_COMMIT_MESSAGE: ${{ steps.prepare_environment.outputs.HEAD_COMMIT_MESSAGE }}
    steps:

      - name: "Prepare environment"
        id: prepare_environment
        run: |
          # Generate VARIABLES
          HEAD_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE//[^a-zA-Z0-9_ .]/}
          ISSUE_ID=$(echo "${{ github.event.head_commit.message }}" | grep -m1 -Po "(LMSDEV|PLA)-[0-9]*" || true)

          # Save them to ENV
          echo "HEAD_COMMIT_MESSAGE=${HEAD_COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
          echo "ISSUE_ID=${ISSUE_ID}" >> "$GITHUB_OUTPUT"

      - name: "Generate Github App Token"
        uses: Aprende-com/devops-workflows/actions/generate-github-token@main
        id: app-token
        with:
          secret_key: ${{ secrets.DEVOPS_APP_SECRET_KEY }}
          app_id: ${{ secrets.DEVOPS_APP_ID }}
          repositories: "devops-workflows"

      - uses: Aprende-com/devops-workflows/actions/slack-notify@main
        if: failure()
        with:
          actor: "${{ github.actor }}"
          title: "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|Deployment> to [master]: ${{ job.status }}"
          status: "${{ job.status }}"
          text: "See <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} #${{ github.run_number }}> for more information"

  reusable-job:
    uses: Aprende-com/devops-workflows/.github/workflows/single_plugin_pipeline_master_reusable.yml@main
    needs: single_plugin_pipeline_dispatch
    secrets: inherit
    with:
      repository: "${{ github.repository }}"
      sha: "${{ github.sha }}"
      actor: "${{ github.actor }}"
      head_commit_message: "${{ needs.single_plugin_pipeline_dispatch.outputs.HEAD_COMMIT_MESSAGE }}"
      issue_id: "${{ needs.single_plugin_pipeline_dispatch.outputs.ISSUE_ID }}"